---
title: "使用贝叶斯方法构建逻辑回归"
author: "黄建祺"
date: "2022-06-15"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

### 使用MCMC对参数后验进行抽样

```{r,echo=TRUE,warning=FALSE,error=FALSE}
library("coda")
library("ggplot2")
library("dplyr")
library("palmerpenguins")
rm(list=ls())
logit<- function(param,x){
  pi<- 1/(1+exp(-(x*param[1]+param[2])))
  return(pi)
}
gentoo<-penguins %>%
  mutate(gender = if_else(sex == "male", 1, 0))
data=data.frame(gentoo$body_mass_g,gentoo$gender)

x=data$gentoo.body_mass_g
y=data$gentoo.gender
trueA <- 0.2
trueB <- 0.1
param=cbind(trueA,trueB)

sampleSize <- nrow(data)
model_logit <- glm(
  y ~ 0 + x,
  data = data,
  family = binomial(link = "logit")
)
ggplot(data = data)+
  geom_point(aes(x=gentoo.body_mass_g,y=gentoo.gender))
likelihood<-function(param){
  a = param[1:2]
  li<-sum(y*log(logit(a,x))+(1-y)*log(1-logit(a,x)))
  return(li)
}
prior <- function(param){
  a = param[1]
  b = param[2]
  aprior = dunif(a, min=0, max=5, log = T)
  bprior = dnorm(b, sd = 2, log = T)
  return(aprior+bprior)
}

proposalfunction <- function(param){
  return(rnorm(2,mean = param, sd= c(0.1,0.1)))
}
```

### 验证后验是否收敛

```{r,echo=TRUE}
run_metropolis_MCMC <- function(startvalue, iterations){
  chain = array(dim = c(iterations+1,2))
  chain[1,] = startvalue
  for (i in 1:iterations){
    proposal = proposalfunction(chain[i,])
    probab = exp(likelihood(proposal)+ prior(proposal) - likelihood(chain[i,])- prior(chain[i,]))
    probab
    if (runif(1) < probab&!is.na(probab)){
      chain[i+1,] = proposal
    }else{
      chain[i+1,] = chain[i,]
    }
  }
  par(mfcol=c(1,2))
  return(mcmc(chain))
}
```

```{r,echo=TRUE,eval=TRUE}
startvalue = c(0,0)
sv2=c(1,1)
chain = run_metropolis_MCMC(startvalue, 10000)
chain_data=data.frame(chain)

summary(chain)
traceplot(chain)

```

### 与现成的逻辑回归的R实现比较
```{r,echo=TRUE}
model_logit <- glm(
  data$gentoo.gender ~ 0 + data$gentoo.body_mass_g,
  data = data,
  family = binomial(link = "logit")
)
summary(model_logit)
```

### 使用贝叶斯MCMC方法对模型估计的优势

-   可以对于参数估计在参数空间上的展现相对于频率学派；
-   MCMC方法可以对于非共轭的分布来进行参数估计，得到广泛的应用在复杂分布上
-   两者的结合使得贝叶斯方法在模型估计上得到更为有效的应用，如机器学习、参数估计等；
